#%RAML 1.0 Library
 
traits:
  errorResp: !include ../Traits/errorResponsesTrait.raml
 
securitySchemes:
  customSecurity: !include ../SecuritySchemes/customSecurityScheme.raml
 
resourceTypes:
  bankCollection:
    is: [errorResp]   
    securedBy:
      - customSecurity    
    get?:
      description: This is used to fetch <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              example: <<getResponse>>
    post?:
      description: This is used create <<resourcePathName>>
      body:
        application/json:
          type: <<postBodyType>>  
          example: <<postBody>>
      responses:
        201:
          body:
            application/json:
              example: <<postResponse>> 
